### ISSUE TITLE
Is it actually that good?

### ISSUE THREAD

**Issue by gguio** [igocreate/igo-dust#9]
Sorry, it's not really an issue but I was searching for a template engine for my website and I stumbled upon your benchmarks and it looks very impressive. Is it production ready and is it still maintained?

**Comment by arnaudm** [comment]
Hi!
Yes it is production ready as it is currently used in many of our projects in production and it works very well.
It is also maintained by our team.

**Comment by gguio** [comment]
thanks, I'll give it a try
